export type Category = {
  slug: string;
  name: string;
};

export type AgeGroup = "0-6m" | "6-12m" | "1-2y" | "2-4y";

export const AGE_GROUPS: { value: AgeGroup; label: string }[] = [
  { value: "0-6m", label: "0–6 months" },
  { value: "6-12m", label: "6–12 months" },
  { value: "1-2y", label: "1–2 years" },
  { value: "2-4y", label: "2–4 years" },
];

export type Product = {
  slug: string;
  name: string;
  category: string;
  price: number;
  oldPrice?: number;
  ages: AgeGroup[];
  sizes: string[];
  colors: string[];
  images: string[];
  description: string;
  featured?: boolean;
};

export const categories: Category[] = [
  { slug: "baby-clothing", name: "Shop" },
  { slug: "clothing", name: "Baby Clothing" },
  { slug: "shoes", name: "Shoes" },
  { slug: "ladies-clothing", name: "Ladies Clothing" },
  { slug: "ladies-bag", name: "Ladies Bag" },
];

export function categoryBySlug(slug: string | undefined): Category | undefined {
  return categories.find((c) => c.slug === slug);
}

export function productBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function relatedProducts(product: Product, count = 4): Product[] {
  return products.filter((p) => p.category === product.category && p.slug !== product.slug).slice(0, count);
}

export const products: Product[] = [
  {
    slug: "cloud-cotton-romper",
    name: "Cloud Cotton Romper",
    category: "clothing",
    price: 450,
    oldPrice: 550,
    ages: ["0-6m", "6-12m"],
    sizes: ["0–3m", "3–6m", "6–9m"],
    colors: ["Sky", "Cream", "Mint"],
    images: ["/products/cloud-cotton-romper-a.jpg", "/products/cloud-cotton-romper-b.jpg"],
    description:
      "Buttery-soft 100% cotton romper with snap closures for quick changes. Gentle on newborn skin and easy to wash.",
    featured: true,
  },
  {
    slug: "blossom-party-frock",
    name: "Blossom Party Frock",
    category: "clothing",
    price: 780,
    ages: ["6-12m", "1-2y"],
    sizes: ["6–12m", "12–18m", "18–24m"],
    colors: ["Blush", "Lilac"],
    images: ["/products/blossom-party-frock-a.jpg", "/products/blossom-party-frock-b.jpg"],
    description:
      "A layered frock with a soft tulle skirt and satin bow, perfect for Eid, birthdays and family photos.",
    featured: true,
  },
  {
    slug: "sunny-tee-shorts-set",
    name: "Sunny Tee & Shorts Set",
    category: "clothing",
    price: 520,
    ages: ["1-2y", "2-4y"],
    sizes: ["1–2y", "2–3y", "3–4y"],
    colors: ["Butter", "Sky"],
    images: ["/products/sunny-tee-shorts-set-a.jpg", "/products/sunny-tee-shorts-set-b.jpg"],
    description:
      "Breathable summer set with a playful print tee and elastic-waist shorts for all-day play.",
  },
  {
    slug: "cozy-fleece-hoodie",
    name: "Cozy Fleece Hoodie",
    category: "clothing",
    price: 650,
    oldPrice: 720,
    ages: ["6-12m", "1-2y"],
    sizes: ["6–12m", "12–18m", "18–24m"],
    colors: ["Peach", "Mint"],
    images: ["/products/cozy-fleece-hoodie-a.jpg", "/products/cozy-fleece-hoodie-b.jpg"],
    description:
      "Brushed fleece hoodie with kangaroo pocket to keep little ones warm through winter mornings.",
    featured: true,
  },
  {
    slug: "starry-pajama-set",
    name: "Starry Night Pajama Set",
    category: "clothing",
    price: 480,
    ages: ["0-6m", "6-12m", "1-2y"],
    sizes: ["0–3m", "3–6m", "6–12m", "1–2y"],
    colors: ["Sky", "Lilac"],
    images: ["/products/starry-pajama-set-a.jpg", "/products/starry-pajama-set-b.jpg"],
    description:
      "Soft jersey pajama set with fold-over mittens so sleepy hands stay warm and scratch-free.",
  },
  {
    slug: "tiny-traveller-dungaree",
    name: "Tiny Traveller Dungaree",
    category: "clothing",
    price: 690,
    ages: ["6-12m", "1-2y", "2-4y"],
    sizes: ["6–12m", "1–2y", "2–3y"],
    colors: ["Butter", "Denim Blue"],
    images: ["/products/tiny-traveller-dungaree-a.jpg", "/products/tiny-traveller-dungaree-b.jpg"],
    description:
      "Adjustable-strap dungaree in sturdy twill that survives crawls, spills and first steps.",
  },
  {
    slug: "first-steps-booties",
    name: "First Steps Booties",
    category: "shoes",
    price: 320,
    ages: ["0-6m", "6-12m"],
    sizes: ["0–3m", "3–6m", "6–9m"],
    colors: ["Cream", "Blush"],
    images: ["/products/first-steps-booties-a.svg", "/products/first-steps-booties-b.svg"],
    description:
      "Featherlight booties with non-slip soles and a snug ankle cuff for wobbly first adventures.",
    featured: true,
  },
  {
    slug: "mini-sneakers",
    name: "Mini Sneakers",
    category: "shoes",
    price: 450,
    ages: ["1-2y", "2-4y"],
    sizes: ["4UK", "5UK", "6UK"],
    colors: ["White", "Sky"],
    images: ["/products/mini-sneakers-a.svg", "/products/mini-sneakers-b.svg"],
    description:
      "Cushioned velcro sneakers with breathable mesh lining — easy on, easy off, hard to outgrow in style.",
  },
  {
    slug: "summer-sandals",
    name: "Summer Sandals",
    category: "shoes",
    price: 380,
    ages: ["1-2y", "2-4y"],
    sizes: ["4UK", "5UK", "6UK"],
    colors: ["Butter", "Peach"],
    images: ["/products/summer-sandals-a.svg", "/products/summer-sandals-b.svg"],
    description:
      "Open-toe sandals with soft padded straps that protect little toes on hot summer days.",
  },
  {
    slug: "sunshine-cap-mitten-set",
    name: "Sunshine Cap & Mitten Set",
    category: "caps-mittens",
    price: 260,
    ages: ["0-6m", "6-12m"],
    sizes: ["0–6m", "6–12m"],
    colors: ["Butter", "Mint"],
    images: ["/products/sunshine-cap-mitten-set-a.svg", "/products/sunshine-cap-mitten-set-b.svg"],
    description:
      "Matching cotton cap and no-scratch mittens that keep tiny heads warm and cheeks unscratched.",
    featured: true,
  },
  {
    slug: "pom-pom-beanie",
    name: "Pom-Pom Winter Beanie",
    category: "caps-mittens",
    price: 240,
    ages: ["0-6m", "6-12m", "1-2y"],
    sizes: ["0–6m", "6–12m", "1–2y"],
    colors: ["Blush", "Lilac", "Sky"],
    images: ["/products/pom-pom-beanie-a.svg", "/products/pom-pom-beanie-b.svg"],
    description:
      "Chunky-knit beanie with a fluffy pom and soft fleece lining for chilly Dimla mornings.",
  },
  {
    slug: "soft-cotton-mittens",
    name: "Soft Cotton Mittens",
    category: "caps-mittens",
    price: 150,
    ages: ["0-6m"],
    sizes: ["0–3m", "3–6m"],
    colors: ["Cream", "Sky"],
    images: ["/products/soft-cotton-mittens-a.svg", "/products/soft-cotton-mittens-b.svg"],
    description:
      "Gentle elastic-cuff mittens woven from breathable cotton so newborn hands stay cozy.",
  },
  {
    slug: "cloud-socks-pack",
    name: "Cloud Socks — 3 Pairs",
    category: "accessories",
    price: 210,
    ages: ["0-6m", "6-12m", "1-2y"],
    sizes: ["0–6m", "6–12m", "1–2y"],
    colors: ["Mixed Pastels"],
    images: ["/products/cloud-socks-pack-a.svg", "/products/cloud-socks-pack-b.svg"],
    description:
      "Three pairs of stay-up cotton socks in pastel shades — soft ribbed cuffs that never leave marks.",
    featured: true,
  },
  {
    slug: "waterproof-feeding-bibs",
    name: "Waterproof Feeding Bibs — 2 pcs",
    category: "accessories",
    price: 190,
    ages: ["6-12m", "1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mint", "Peach"],
    images: ["/products/waterproof-feeding-bibs-a.svg", "/products/waterproof-feeding-bibs-b.svg"],
    description:
      "Wipe-clean waterproof bibs with a crumb-catching pocket, ready for weaning messes.",
  },
  {
    slug: "baby-item-01",
    name: "Baby Item 01",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-01.jpg", "/products/baby-02.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "baby-item-02",
    name: "Baby Item 02",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-03.jpg", "/products/baby-04.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "baby-item-03",
    name: "Baby Item 03",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-05.jpg", "/products/baby-06.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "baby-item-04",
    name: "Baby Item 04",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-07.jpg", "/products/baby-08.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "baby-item-05",
    name: "Baby Item 05",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-09.jpg", "/products/baby-10.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "baby-item-06",
    name: "Baby Item 06",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-11.jpg", "/products/baby-12.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "baby-item-07",
    name: "Baby Item 07",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-13.jpg", "/products/baby-14.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "baby-item-08",
    name: "Baby Item 08",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-15.jpg", "/products/baby-16.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "baby-item-09",
    name: "Baby Item 09",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-17.jpg", "/products/baby-18.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "baby-item-10",
    name: "Baby Item 10",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-19.jpg", "/products/baby-20.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "baby-item-11",
    name: "Baby Item 11",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-21.jpg", "/products/baby-22.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "baby-item-12",
    name: "Baby Item 12",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-23.jpg", "/products/baby-24.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "baby-item-13",
    name: "Baby Item 13",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-25.jpg", "/products/baby-26.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "baby-item-14",
    name: "Baby Item 14",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-27.jpg", "/products/baby-28.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "baby-item-15",
    name: "Baby Item 15",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-29.jpg", "/products/baby-30.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "baby-item-16",
    name: "Baby Item 16",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-31.jpg", "/products/baby-32.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "baby-item-17",
    name: "Baby Item 17",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-33.jpg", "/products/baby-34.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "baby-item-18",
    name: "Baby Item 18",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-35.jpg", "/products/baby-36.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "baby-item-19",
    name: "Baby Item 19",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-37.jpg", "/products/baby-38.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "baby-item-20",
    name: "Baby Item 20",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-39.jpg", "/products/baby-40.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "baby-item-21",
    name: "Baby Item 21",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-41.jpg", "/products/baby-42.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "baby-item-22",
    name: "Baby Item 22",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-43.jpg", "/products/baby-44.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "baby-item-23",
    name: "Baby Item 23",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-45.jpg", "/products/baby-45.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "baby-item-24",
    name: "Baby Item 24",
    category: "clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: [
      "/products/izabelly-marques-Rc3I6Ip4dKI-unsplash.jpg",
      "/products/izabelly-marques-Rc3I6Ip4dKI-unsplash.jpg",
    ],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "baby-item-25",
    name: "Baby Item 25",
    category: "clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: [
      "/products/kayan-baby-yf-J_iKlFpY-unsplash.jpg",
      "/products/kayan-baby-yf-J_iKlFpY-unsplash.jpg",
    ],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "baby-item-26",
    name: "Baby Item 26",
    category: "clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: [
      "/products/petra-ticic-tWVnxEciOk0-unsplash.jpg",
      "/products/petra-ticic-tWVnxEciOk0-unsplash.jpg",
    ],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-01",
    name: "Ladies Item 01",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-01.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-02",
    name: "Ladies Item 02",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-02.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-03",
    name: "Ladies Item 03",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-03.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-04",
    name: "Ladies Item 04",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-04.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-05",
    name: "Ladies Item 05",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-05.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-06",
    name: "Ladies Item 06",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-06.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-07",
    name: "Ladies Item 07",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-07.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-08",
    name: "Ladies Item 08",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-08.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-09",
    name: "Ladies Item 09",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-09.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-10",
    name: "Ladies Item 10",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-10.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-11",
    name: "Ladies Item 11",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-11.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-12",
    name: "Ladies Item 12",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-12.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-13",
    name: "Ladies Item 13",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-13.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-14",
    name: "Ladies Item 14",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-14.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-15",
    name: "Ladies Item 15",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-15.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-16",
    name: "Ladies Item 16",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-16.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-17",
    name: "Ladies Item 17",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-17.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-18",
    name: "Ladies Item 18",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-18.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-19",
    name: "Ladies Item 19",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-19.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-20",
    name: "Ladies Item 20",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-20.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-21",
    name: "Ladies Item 21",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-21.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-22",
    name: "Ladies Item 22",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-22.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-23",
    name: "Ladies Item 23",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-23.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-24",
    name: "Ladies Item 24",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-24.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-25",
    name: "Ladies Item 25",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-25.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-26",
    name: "Ladies Item 26",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-26.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-27",
    name: "Ladies Item 27",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-27.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-28",
    name: "Ladies Item 28",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-28.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-29",
    name: "Ladies Item 29",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-29.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-30",
    name: "Ladies Item 30",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-30.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-31",
    name: "Ladies Item 31",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-31.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-32",
    name: "Ladies Item 32",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-32.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-33",
    name: "Ladies Item 33",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-33.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-34",
    name: "Ladies Item 34",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-34.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-35",
    name: "Ladies Item 35",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-35.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-36",
    name: "Ladies Item 36",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-36.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-37",
    name: "Ladies Item 37",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-37.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-38",
    name: "Ladies Item 38",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-38.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-39",
    name: "Ladies Item 39",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-39.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-40",
    name: "Ladies Item 40",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-40.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-41",
    name: "Ladies Item 41",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-41.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-42",
    name: "Ladies Item 42",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-42.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-43",
    name: "Ladies Item 43",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-43.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-44",
    name: "Ladies Item 44",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-44.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-45",
    name: "Ladies Item 45",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-45.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-46",
    name: "Ladies Item 46",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-46.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-item-47",
    name: "Ladies Item 47",
    category: "ladies-clothing",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-new-47.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-bag-01",
    name: "Ladies Handbag 01",
    category: "ladies-bag",
    price: 850,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Black", "Brown"],
    images: ["/products/ladies-bag-01.jpg", "/products/ladies-bag-01.jpg"],
    description: "Stylish handbag from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-bag-02",
    name: "Ladies Handbag 02",
    category: "ladies-bag",
    price: 950,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Red", "Pink"],
    images: ["/products/ladies-bag-02.jpg", "/products/ladies-bag-02.jpg"],
    description: "Premium tote bag from the Chilahati Ladies and Baby Mart collection.",
  },
  {
    slug: "ladies-bag-03",
    name: "Ladies Shoulder Bag",
    category: "ladies-bag",
    price: 750,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Beige", "Black"],
    images: ["/products/ladies-bag-03.jpg", "/products/ladies-bag-03.jpg"],
    description: "Casual shoulder bag from the Chilahati Ladies and Baby Mart collection.",
  },
];
