export type Category = {
  slug: string;
  name: string;
  nameBn: string;
};

export type AgeGroup = "0-6m" | "6-12m" | "1-2y" | "2-4y";

export const AGE_GROUPS: { value: AgeGroup; label: string; labelBn: string }[] = [
  { value: "0-6m", label: "0–6 months", labelBn: "০–৬ মাস" },
  { value: "6-12m", label: "6–12 months", labelBn: "৬–১২ মাস" },
  { value: "1-2y", label: "1–2 years", labelBn: "১–২ বছর" },
  { value: "2-4y", label: "2–4 years", labelBn: "২–৪ বছর" },
];

export type Product = {
  slug: string;
  name: string;
  nameBn: string;
  category: string;
  price: number;
  oldPrice?: number;
  ages: AgeGroup[];
  sizes: string[];
  colors: string[];
  images: [string, string];
  description: string;
  descriptionBn: string;
  featured?: boolean;
};

export const categories: Category[] = [
  { slug: "clothing", name: "Baby Clothing", nameBn: "শিশুতোষ জামা-কাপড়" },
  { slug: "baby-clothing", name: "Baby Collection", nameBn: "বেবি কালেকশন" },
  { slug: "shoes", name: "Ladies Clothing", nameBn: "লেডিস ক্লদিং" },
  { slug: "ladies-bag", name: "Ladies Bag", nameBn: "লেডিস ব্যাগ" },
];

export function categoryBySlug(slug: string | undefined): Category | undefined {
  return categories.find((c) => c.slug === slug);
}

export function productBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function relatedProducts(product: Product, count = 4): Product[] {
  return products.filter((p) => p.category === product.category && p.slug !== product.slug).slice(0, count);
}

export const products: Product[] = [
  {
    slug: "cloud-cotton-romper",
    name: "Cloud Cotton Romper",
    nameBn: "ক্লাউড কটন রম্পার",
    category: "clothing",
    price: 450,
    oldPrice: 550,
    ages: ["0-6m", "6-12m"],
    sizes: ["0–3m", "3–6m", "6–9m"],
    colors: ["Sky", "Cream", "Mint"],
    images: ["/products/cloud-cotton-romper-a.jpg", "/products/cloud-cotton-romper-b.jpg"],
    description:
      "Buttery-soft 100% cotton romper with snap closures for quick changes. Gentle on newborn skin and easy to wash.",
    descriptionBn: "১০০% কটনের নরম রম্পার, নবজাতকের ত্বকের জন্য একদম নিরাপদ।",
    featured: true,
  },
  {
    slug: "blossom-party-frock",
    name: "Blossom Party Frock",
    nameBn: "ব্লসম পার্টি ফ্রক",
    category: "clothing",
    price: 780,
    ages: ["6-12m", "1-2y"],
    sizes: ["6–12m", "12–18m", "18–24m"],
    colors: ["Blush", "Lilac"],
    images: ["/products/blossom-party-frock-a.jpg", "/products/blossom-party-frock-b.jpg"],
    description:
      "A layered frock with a soft tulle skirt and satin bow, perfect for Eid, birthdays and family photos.",
    descriptionBn: "ঈদ, জন্মদিন কিংবা অনুষ্ঠানে আপনার মণিকে সাজান এই প্রিটি ফ্রকে।",
    featured: true,
  },
  {
    slug: "sunny-tee-shorts-set",
    name: "Sunny Tee & Shorts Set",
    nameBn: "সানি টি-শার্ট ও শর্টস সেট",
    category: "clothing",
    price: 520,
    ages: ["1-2y", "2-4y"],
    sizes: ["1–2y", "2–3y", "3–4y"],
    colors: ["Butter", "Sky"],
    images: ["/products/sunny-tee-shorts-set-a.jpg", "/products/sunny-tee-shorts-set-b.jpg"],
    description:
      "Breathable summer set with a playful print tee and elastic-waist shorts for all-day play.",
    descriptionBn: "গরমের জন্য আরামদায়ক হালকা সেট, সারাদিন খেলাধুলার জন্য পারফেক্ট।",
  },
  {
    slug: "cozy-fleece-hoodie",
    name: "Cozy Fleece Hoodie",
    nameBn: "কোজি ফ্লিস হুডি",
    category: "clothing",
    price: 650,
    oldPrice: 720,
    ages: ["6-12m", "1-2y"],
    sizes: ["6–12m", "12–18m", "18–24m"],
    colors: ["Peach", "Mint"],
    images: ["/products/cozy-fleece-hoodie-a.jpg", "/products/cozy-fleece-hoodie-b.jpg"],
    description:
      "Brushed fleece hoodie with kangaroo pocket to keep little ones warm through winter mornings.",
    descriptionBn: "শীতের সকালে গরম রাখার জন্য নরম ফ্লিসের হুডি জ্যাকেট।",
    featured: true,
  },
  {
    slug: "starry-pajama-set",
    name: "Starry Night Pajama Set",
    nameBn: "স্টারি নাইট পায়জামা সেট",
    category: "clothing",
    price: 480,
    ages: ["0-6m", "6-12m", "1-2y"],
    sizes: ["0–3m", "3–6m", "6–12m", "1–2y"],
    colors: ["Sky", "Lilac"],
    images: ["/products/starry-pajama-set-a.jpg", "/products/starry-pajama-set-b.jpg"],
    description:
      "Soft jersey pajama set with fold-over mittens so sleepy hands stay warm and scratch-free.",
    descriptionBn: "ঘুমের জন্য আরামদায়ক নরম পায়জামা সেট, হাত-পা ঠান্ডা লাগবে না।",
  },
  {
    slug: "tiny-traveller-dungaree",
    name: "Tiny Traveller Dungaree",
    nameBn: "টাইনি ট্রাভেলার ডাঙ্গারি",
    category: "clothing",
    price: 690,
    ages: ["6-12m", "1-2y", "2-4y"],
    sizes: ["6–12m", "1–2y", "2–3y"],
    colors: ["Butter", "Denim Blue"],
    images: ["/products/tiny-traveller-dungaree-a.jpg", "/products/tiny-traveller-dungaree-b.jpg"],
    description:
      "Adjustable-strap dungaree in sturdy twill that survives crawls, spills and first steps.",
    descriptionBn: "টেকসই টুইল কাপড়ের ডাঙ্গারি, চলাফেরায় আরামদায়ক ও মজবুত।",
  },
  {
    slug: "first-steps-booties",
    name: "First Steps Booties",
    nameBn: "ফার্স্ট স্টেপস বুটি",
    category: "shoes",
    price: 320,
    ages: ["0-6m", "6-12m"],
    sizes: ["0–3m", "3–6m", "6–9m"],
    colors: ["Cream", "Blush"],
    images: ["/products/first-steps-booties-a.svg", "/products/first-steps-booties-b.svg"],
    description:
      "Featherlight booties with non-slip soles and a snug ankle cuff for wobbly first adventures.",
    descriptionBn: "হালকা ও পিচ্ছিল-না-হওয়া সোলের নরম বুটি, প্রথম হাঁটার জন্য আদর্শ।",
    featured: true,
  },
  {
    slug: "mini-sneakers",
    name: "Mini Sneakers",
    nameBn: "মিনি স্নিকার্স",
    category: "shoes",
    price: 450,
    ages: ["1-2y", "2-4y"],
    sizes: ["4UK", "5UK", "6UK"],
    colors: ["White", "Sky"],
    images: ["/products/mini-sneakers-a.svg", "/products/mini-sneakers-b.svg"],
    description:
      "Cushioned velcro sneakers with breathable mesh lining — easy on, easy off, hard to outgrow in style.",
    descriptionBn: "ভেলক্রোযুক্ত আরামদায়ক স্নিকার্স, পরা ও খোলা দুটোই সহজ।",
  },
  {
    slug: "summer-sandals",
    name: "Summer Sandals",
    nameBn: "সামার স্যান্ডেল",
    category: "shoes",
    price: 380,
    ages: ["1-2y", "2-4y"],
    sizes: ["4UK", "5UK", "6UK"],
    colors: ["Butter", "Peach"],
    images: ["/products/summer-sandals-a.svg", "/products/summer-sandals-b.svg"],
    description:
      "Open-toe sandals with soft padded straps that protect little toes on hot summer days.",
    descriptionBn: "গরমের দিনে আরামদায়ক নরম স্ট্র্যাপের স্যান্ডেল।",
  },
  {
    slug: "sunshine-cap-mitten-set",
    name: "Sunshine Cap & Mitten Set",
    nameBn: "সানশাইন ক্যাপ ও মিটেন্স সেট",
    category: "caps-mittens",
    price: 260,
    ages: ["0-6m", "6-12m"],
    sizes: ["0–6m", "6–12m"],
    colors: ["Butter", "Mint"],
    images: ["/products/sunshine-cap-mitten-set-a.svg", "/products/sunshine-cap-mitten-set-b.svg"],
    description:
      "Matching cotton cap and no-scratch mittens that keep tiny heads warm and cheeks unscratched.",
    descriptionBn: "ম্যাচিং কটন ক্যাপ ও মিটেন্স সেট, মাথা গরম রাখে আর নখের আঁচড় থেকে বাঁচায়।",
    featured: true,
  },
  {
    slug: "pom-pom-beanie",
    name: "Pom-Pom Winter Beanie",
    nameBn: "পম-পম উইন্টার বিনি",
    category: "caps-mittens",
    price: 240,
    ages: ["0-6m", "6-12m", "1-2y"],
    sizes: ["0–6m", "6–12m", "1–2y"],
    colors: ["Blush", "Lilac", "Sky"],
    images: ["/products/pom-pom-beanie-a.svg", "/products/pom-pom-beanie-b.svg"],
    description:
      "Chunky-knit beanie with a fluffy pom and soft fleece lining for chilly Dimla mornings.",
    descriptionBn: "শীতের ঠান্ডার জন্য ফ্লিস-লাইনিংযুক্ত মোটা বুননের বিনি টুপি।",
  },
  {
    slug: "soft-cotton-mittens",
    name: "Soft Cotton Mittens",
    nameBn: "সফট কটন মিটেন্স",
    category: "caps-mittens",
    price: 150,
    ages: ["0-6m"],
    sizes: ["0–3m", "3–6m"],
    colors: ["Cream", "Sky"],
    images: ["/products/soft-cotton-mittens-a.svg", "/products/soft-cotton-mittens-b.svg"],
    description:
      "Gentle elastic-cuff mittens woven from breathable cotton so newborn hands stay cozy.",
    descriptionBn: "নবজাতকের ছোট্ট হাতের জন্য নরম সুতির মিটেন্স।",
  },
  {
    slug: "cloud-socks-pack",
    name: "Cloud Socks — 3 Pairs",
    nameBn: "ক্লাউড মোজা — ৩ পেয়ার",
    category: "accessories",
    price: 210,
    ages: ["0-6m", "6-12m", "1-2y"],
    sizes: ["0–6m", "6–12m", "1–2y"],
    colors: ["Mixed Pastels"],
    images: ["/products/cloud-socks-pack-a.svg", "/products/cloud-socks-pack-b.svg"],
    description:
      "Three pairs of stay-up cotton socks in pastel shades — soft ribbed cuffs that never leave marks.",
    descriptionBn: "প্যাস্টেল রঙের তিন পেয়ার নরম সুতির মোজা, চাপড়া ছাড়াই থাকে ঝোলায়।",
    featured: true,
  },
  {
    slug: "waterproof-feeding-bibs",
    name: "Waterproof Feeding Bibs — 2 pcs",
    nameBn: "ওয়াটারপ্রুফ ফিডিং বিব — ২টি",
    category: "accessories",
    price: 190,
    ages: ["6-12m", "1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mint", "Peach"],
    images: ["/products/waterproof-feeding-bibs-a.svg", "/products/waterproof-feeding-bibs-b.svg"],
    description:
      "Wipe-clean waterproof bibs with a crumb-catching pocket, ready for weaning messes.",
    descriptionBn: "পরিষ্কার করা সহজ ওয়াটারপ্রুফ বিব, খাওয়ানোর ঝামেলা অনেক কমিয়ে দেয়।",
  },
  {
    slug: "baby-item-01",
    name: "Baby Item 01",
    nameBn: "বেবি আইটেম 1",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-01.jpg", "/products/baby-02.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন শিশুতোষ পোশাক।",
  },
  {
    slug: "baby-item-02",
    name: "Baby Item 02",
    nameBn: "বেবি আইটেম 2",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-03.jpg", "/products/baby-04.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন শিশুতোষ পোশাক।",
  },
  {
    slug: "baby-item-03",
    name: "Baby Item 03",
    nameBn: "বেবি আইটেম 3",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-05.jpg", "/products/baby-06.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন শিশুতোষ পোশাক।",
  },
  {
    slug: "baby-item-04",
    name: "Baby Item 04",
    nameBn: "বেবি আইটেম 4",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-07.jpg", "/products/baby-08.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন শিশুতোষ পোশাক।",
  },
  {
    slug: "baby-item-05",
    name: "Baby Item 05",
    nameBn: "বেবি আইটেম 5",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-09.jpg", "/products/baby-10.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন শিশুতোষ পোশাক।",
  },
  {
    slug: "baby-item-06",
    name: "Baby Item 06",
    nameBn: "বেবি আইটেম 6",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-11.jpg", "/products/baby-12.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন শিশুতোষ পোশাক।",
  },
  {
    slug: "baby-item-07",
    name: "Baby Item 07",
    nameBn: "বেবি আইটেম 7",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-13.jpg", "/products/baby-14.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন শিশুতোষ পোশাক।",
  },
  {
    slug: "baby-item-08",
    name: "Baby Item 08",
    nameBn: "বেবি আইটেম 8",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-15.jpg", "/products/baby-16.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন শিশুতোষ পোশাক।",
  },
  {
    slug: "baby-item-09",
    name: "Baby Item 09",
    nameBn: "বেবি আইটেম 9",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-17.jpg", "/products/baby-18.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন শিশুতোষ পোশাক।",
  },
  {
    slug: "baby-item-10",
    name: "Baby Item 10",
    nameBn: "বেবি আইটেম 10",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-19.jpg", "/products/baby-20.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন শিশুতোষ পোশাক।",
  },
  {
    slug: "baby-item-11",
    name: "Baby Item 11",
    nameBn: "বেবি আইটেম 11",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-21.jpg", "/products/baby-22.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন শিশুতোষ পোশাক।",
  },
  {
    slug: "baby-item-12",
    name: "Baby Item 12",
    nameBn: "বেবি আইটেম 12",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-23.jpg", "/products/baby-24.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন শিশুতোষ পোশাক।",
  },
  {
    slug: "baby-item-13",
    name: "Baby Item 13",
    nameBn: "বেবি আইটেম 13",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-25.jpg", "/products/baby-26.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন শিশুতোষ পোশাক।",
  },
  {
    slug: "baby-item-14",
    name: "Baby Item 14",
    nameBn: "বেবি আইটেম 14",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-27.jpg", "/products/baby-28.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন শিশুতোষ পোশাক।",
  },
  {
    slug: "baby-item-15",
    name: "Baby Item 15",
    nameBn: "বেবি আইটেম 15",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-29.jpg", "/products/baby-30.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন শিশুতোষ পোশাক।",
  },
  {
    slug: "baby-item-16",
    name: "Baby Item 16",
    nameBn: "বেবি আইটেম 16",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-31.jpg", "/products/baby-32.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন শিশুতোষ পোশাক।",
  },
  {
    slug: "baby-item-17",
    name: "Baby Item 17",
    nameBn: "বেবি আইটেম 17",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-33.jpg", "/products/baby-34.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন শিশুতোষ পোশাক।",
  },
  {
    slug: "baby-item-18",
    name: "Baby Item 18",
    nameBn: "বেবি আইটেম 18",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-35.jpg", "/products/baby-36.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন শিশুতোষ পোশাক।",
  },
  {
    slug: "baby-item-19",
    name: "Baby Item 19",
    nameBn: "বেবি আইটেম 19",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-37.jpg", "/products/baby-38.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন শিশুতোষ পোশাক।",
  },
  {
    slug: "baby-item-20",
    name: "Baby Item 20",
    nameBn: "বেবি আইটেম 20",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-39.jpg", "/products/baby-40.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন শিশুতোষ পোশাক।",
  },
  {
    slug: "baby-item-21",
    name: "Baby Item 21",
    nameBn: "বেবি আইটেম 21",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-41.jpg", "/products/baby-42.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন শিশুতোষ পোশাক।",
  },
  {
    slug: "baby-item-22",
    name: "Baby Item 22",
    nameBn: "বেবি আইটেম 22",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-43.jpg", "/products/baby-44.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন শিশুতোষ পোশাক।",
  },
  {
    slug: "baby-item-23",
    name: "Baby Item 23",
    nameBn: "বেবি আইটেম 23",
    category: "baby-clothing",
    price: 350,
    ages: ["0-6m", "6-12m", "1-2y", "2-4y"],
    sizes: ["0-6m", "6-12m", "1-2y", "2-4y"],
    colors: ["Mixed"],
    images: ["/products/baby-45.jpg", "/products/baby-45.jpg"],
    description: "Quality baby clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন শিশুতোষ পোশাক।",
  },
  {
    slug: "ladies-item-01",
    name: "Ladies Item 01",
    nameBn: "লেডিস আইটেম 1",
    category: "shoes",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-01.jpg", "/products/ladies-01.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন লেডিস পোশাক।",
  },
  {
    slug: "ladies-item-02",
    name: "Ladies Item 02",
    nameBn: "লেডিস আইটেম 2",
    category: "shoes",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-02.jpg", "/products/ladies-02.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন লেডিস পোশাক।",
  },
  {
    slug: "ladies-item-03",
    name: "Ladies Item 03",
    nameBn: "লেডিস আইটেম 3",
    category: "shoes",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-03.jpg", "/products/ladies-03.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন লেডিস পোশাক।",
  },
  {
    slug: "ladies-item-04",
    name: "Ladies Item 04",
    nameBn: "লেডিস আইটেম 4",
    category: "shoes",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-04.jpg", "/products/ladies-04.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন লেডিস পোশাক।",
  },
  {
    slug: "ladies-item-05",
    name: "Ladies Item 05",
    nameBn: "লেডিস আইটেম 5",
    category: "shoes",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-05.jpg", "/products/ladies-05.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন লেডিস পোশাক।",
  },
  {
    slug: "ladies-item-06",
    name: "Ladies Item 06",
    nameBn: "লেডিস আইটেম 6",
    category: "shoes",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-06.jpg", "/products/ladies-06.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন লেডিস পোশাক।",
  },
  {
    slug: "ladies-item-07",
    name: "Ladies Item 07",
    nameBn: "লেডিস আইটেম 7",
    category: "shoes",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-07.jpg", "/products/ladies-07.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন লেডিস পোশাক।",
  },
  {
    slug: "ladies-item-08",
    name: "Ladies Item 08",
    nameBn: "লেডিস আইটেম 8",
    category: "shoes",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-08.jpg", "/products/ladies-08.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন লেডিস পোশাক।",
  },
  {
    slug: "ladies-item-09",
    name: "Ladies Item 09",
    nameBn: "লেডিস আইটেম 9",
    category: "shoes",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-09.jpg", "/products/ladies-09.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন লেডিস পোশাক।",
  },
  {
    slug: "ladies-item-10",
    name: "Ladies Item 10",
    nameBn: "লেডিস আইটেম 10",
    category: "shoes",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-10.jpg", "/products/ladies-10.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন লেডিস পোশাক।",
  },
  {
    slug: "ladies-item-11",
    name: "Ladies Item 11",
    nameBn: "লেডিস আইটেম 11",
    category: "shoes",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-11.jpg", "/products/ladies-11.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন লেডিস পোশাক।",
  },
  {
    slug: "ladies-item-12",
    name: "Ladies Item 12",
    nameBn: "লেডিস আইটেম 12",
    category: "shoes",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-12.jpg", "/products/ladies-12.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন লেডিস পোশাক।",
  },
  {
    slug: "ladies-item-13",
    name: "Ladies Item 13",
    nameBn: "লেডিস আইটেম 13",
    category: "shoes",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-13.jpg", "/products/ladies-13.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন লেডিস পোশাক।",
  },
  {
    slug: "ladies-item-14",
    name: "Ladies Item 14",
    nameBn: "লেডিস আইটেম 14",
    category: "shoes",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-14.jpg", "/products/ladies-14.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন লেডিস পোশাক।",
  },
  {
    slug: "ladies-item-15",
    name: "Ladies Item 15",
    nameBn: "লেডিস আইটেম 15",
    category: "shoes",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-15.jpg", "/products/ladies-15.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন লেডিস পোশাক।",
  },
  {
    slug: "ladies-item-16",
    name: "Ladies Item 16",
    nameBn: "লেডিস আইটেম 16",
    category: "shoes",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-16.jpg", "/products/ladies-16.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন লেডিস পোশাক।",
  },
  {
    slug: "ladies-item-17",
    name: "Ladies Item 17",
    nameBn: "লেডিস আইটেম 17",
    category: "shoes",
    price: 650,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Mixed"],
    images: ["/products/ladies-17.jpg", "/products/ladies-17.jpg"],
    description: "Premium ladies clothing from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের মানসম্পন্ন লেডিস পোশাক।",
  },
  {
    slug: "ladies-bag-01",
    name: "Ladies Handbag 01",
    nameBn: "লেডিস হ্যান্ডব্যাগ ১",
    category: "ladies-bag",
    price: 850,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Black", "Brown"],
    images: ["/products/ladies-bag-01.jpg", "/products/ladies-bag-01.jpg"],
    description: "Stylish handbag from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের স্টাইলিশ হ্যান্ডব্যাগ।",
  },
  {
    slug: "ladies-bag-02",
    name: "Ladies Handbag 02",
    nameBn: "লেডিস হ্যান্ডব্যাগ ২",
    category: "ladies-bag",
    price: 950,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Red", "Pink"],
    images: ["/products/ladies-bag-02.jpg", "/products/ladies-bag-02.jpg"],
    description: "Premium tote bag from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের প্রিমিয়াম টোট ব্যাগ।",
  },
  {
    slug: "ladies-bag-03",
    name: "Ladies Shoulder Bag",
    nameBn: "লেডিস শোল্ডার ব্যাগ",
    category: "ladies-bag",
    price: 750,
    ages: ["1-2y", "2-4y"],
    sizes: ["Free Size"],
    colors: ["Beige", "Black"],
    images: ["/products/ladies-bag-03.jpg", "/products/ladies-bag-03.jpg"],
    description: "Casual shoulder bag from the Chilahati Ladies and Baby Mart collection.",
    descriptionBn: "চিলাহাটি লেডিস অ্যান্ড বেবি মার্টের ক্যাজুয়াল শোল্ডার ব্যাগ।",
  },
];
